# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nixl-benchmark
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nixl-benchmark
  template:
    metadata:
      labels:
        app: nixl-benchmark
    spec:
      containers:
      - name: nixl-benchmark
        image: "my-registry/nixlbench:version-arch"
        command: ["sh", "-c"]
        env:
          - name: ETCD_ENDPOINTS
            value: etcd:2379
        args:
        - |
          nixlbench -etcd_endpoints ${ETCD_ENDPOINTS} --target_seg_type VRAM --initiator_seg_type VRAM && sleep infinity
        resources:
          requests:
              cpu: "10"
              memory: "5Gi"
              nvidia.com/gpu: "1"
          limits:
              cpu: "10"
              memory: "5Gi"
              nvidia.com/gpu: "1"
